routes/frontend.php
<?php

// Data required by all views. Navigation Data
use App\Activities;
use App\Destination;
use App\Package;

View::composer(['*frontend.*'], function ($view) {
    $nav_destinations = Destination::orderBy('name', 'asc')->where('slug', '!=', 'tibet')->where('slug', '!=', 'bhutan')->get();
    $nav_packages = Package::orderBy('name', 'asc')->select('name', 'slug')->get();
    $nav_adventures = Activities::orderBy('name', 'asc')->select('name', 'slug')->get();
    $tibet = Destination::where('slug', 'tibet')->select('id')->first();
    $tibet_packages = Package::where('destination_id', $tibet->id)->orderBy('name', 'asc')->select('name', 'slug')->get();
    $bhutan = Destination::where('slug', 'bhutan')->select('id')->first();
    $bhutan_packages = Package::where('destination_id', $bhutan->id)->orderBy('name', 'asc')->select('name', 'slug')->get();

    $view->with('nav_destinations', $nav_destinations)
        ->with('nav_packages', $nav_packages)
        ->with('nav_adventures', $nav_adventures)
        ->with('tibet_packages', $tibet_packages)
        ->with('bhutan_packages', $bhutan_packages);
});

// Login and Register
Route::group(['namespace' => 'Auth'], function () {
    Route::group(['middleware' => 'ifnotloggedin'], function () {
        Route::post('socialLogin/{provider}', 'SocialLoginController@socialSignUp');
        Route::get('/login', 'AuthController@loginForm')->name('login');
        Route::post('/login', 'AuthController@login');
        Route::get('/register', 'AuthController@registerForm')->name('register');
        Route::post('/register', 'AuthController@register');
        Route::any('/register/activate/{token}', 'AuthController@signUpActivate');

        // Password reset
        Route::get('/password', 'PasswordController@requestForm')->name('password.request');
        Route::post('/password', 'PasswordController@request');
        Route::get('/password/{token}', 'PasswordController@resetForm');
        Route::post('/password-reset', 'PasswordController@reset')->name('password.reset');
    });

    Route::group(['middleware' => 'ifloggedin'], function () {
        Route::get('/logout', 'AuthController@logout')->name('logout');
    });
});


Route::group(['namespace' => 'frontend'], function () {

    // Home
    Route::get('/', 'PagesController@landing')->name('home');

    // Destinations
    Route::get('/destination', 'DestinationController@allDestinations')->name('destination');
    Route::get('/destination/{slug}', 'PackageController@showPackages')->name('destination.package');

    // Package
    Route::get('/package', 'PackageController@allPackages')->name('package');
    Route::get('/package/{slug}', 'PackageController@singlePackage')->name('package.show');

    // Adventures
    Route::get('/adventure', 'AdventureController@allAdventures')->name('adventure');
    Route::get('/adventure/{slug}', 'AdventureController@singleAdventure')->name('adventure.show');

    // Blog
    Route::get('/blog', 'BlogController@index')->name('blog');
    Route::get('/blog/{slug}', 'BlogController@show')->name('blog.show');

    // Pages
    Route::get('/about', 'PagesController@aboutNavigation')->name('about');
    Route::get('/contact', 'PagesController@contactNavigation')->name('contact');

    // Enquiry
    Route::post('/enquiry', 'EnquiryController@store')->name('enquiry');

    // Search
    Route::post('/fetch-search-package', 'SearchController@searchPackage')->name('package.fetch');
    Route::post('/fetch-search-destination', 'SearchController@searchDestination')->name('destination.fetch');
    Route::post('/fetch-search-adventure', 'SearchController@searchAdventure')->name('adventure.fetch');

    // Search home
    Route::post('/show-available-package', 'SearchController@showAvailablePackage')->name('package.available');
    Route::post('/show-package-duration', 'SearchController@showPackageDuration')->name('package.duration');

    // Privacy
    Route::get('/privacy-policy', 'PagesController@privacy')->name('privacy');
    Route::get('/why-nepal', 'PagesController@nepal')->name('nepal');
    Route::get('/why-bhutan', 'PagesController@bhutan')->name('bhutan');
    Route::get('/why-tibet', 'PagesController@tibet')->name('tibet');

    // Bookings
    Route::get('/booking/{type}/{slug}', 'BookingController@index')->name('booking');
    Route::post('/booking', 'BookingController@store')->name('booking.store');

    // functions enabled after logged In
    Route::group(['middleware' => 'ifloggedin'], function () {

        Route::group(['prefix' => 'profile'], function () {
            // User Profile
            Route::get('', 'UserController@profile')->name('profile');
            Route::post('', 'UserController@update');

            Route::get('/blog', 'BlogController@blog')->name('profile.blog');
            Route::get('/blog/create', 'BlogController@create')->name('profile.blog.create');
            Route::post('/blog/create', 'BlogController@store');
            Route::get('/blog/edit/{id}', 'BlogController@edit')->name('profile.blog.edit');
            Route::post('/blog/edit/{id}', 'BlogController@update');
            Route::post('/blog/delete/{id}', 'BlogController@destroy')->name('profile.blog.delete');
        });

        Route::post('/review', 'ReviewController@review')->name('package.review');
        Route::post('/review/{id}', 'ReviewController@reviewEdit')->name('package.review.edit');

    });

});

routes/web.php
<?php
require "frontend.php";

Route::group(['prefix' => 'reg@nessem/admin'], function () {

    Route::group(['namespace' => 'auth'], function () {
        Route::get('/login', 'AdminAuthController@loginForm')->name('admin.login');
        Route::post('/login', 'AdminAuthController@login');
        Route::post('/logout', 'AdminAuthController@logout')->name('admin.logout');
    });

    Route::group(['namespace' => 'backend'], function () {
        //main admin dashboard
        Route::group(['middleware' => 'admin'], function () {
            Route::get('/', 'DashboardController@index')->name('dashboard');

            // User
            Route::group(['prefix' => 'users'], function () {
                Route::get('/user', 'UserController@user')->name('user.list');
                Route::get('/user/activate/{id}', 'UserController@activate')->name('user.activate');
                Route::get('/user/block/{id}', 'UserController@block')->name('user.block');
                Route::get('/admin', 'UserController@admin')->name('admin.list');
                Route::post('destroy/{id}', 'UserController@destroy')->name('user.destroy');
            });

            //Destination Route
            Route::group(['prefix' => 'destinations'], function () {
                Route::get('/', 'DestinationController@index')->name('destinations.list');
                Route::get('create', 'DestinationController@create')->name('destinations.create');
                Route::post('create', 'DestinationController@store');
                Route::get('update/{id}', 'DestinationController@edit')->name('destinations.edit');
                Route::patch('update/{id}', 'DestinationController@update');
                Route::post('destroy/{id}', 'DestinationController@destroy')->name('destinations.destroy');
            });

            //Activities and Adventures Routes
            Route::group(['prefix' => 'activity'], function () {
                Route::get('/', 'ActivitiesController@index')->name('activity.list');
                Route::get('create', 'ActivitiesController@create')->name('activity.create');
                Route::post('create', 'ActivitiesController@store');
                Route::get('update/{id}', 'ActivitiesController@edit')->name('activity.edit');
                Route::patch('update/{id}', 'ActivitiesController@update');
                Route::post('destroy/{id}', 'ActivitiesController@destroy')->name('activity.destroy');
            });

            //Packages Routes
            Route::group(['prefix' => 'packages'], function () {
                Route::get('/', 'PackageController@index')->name('package.list');
                Route::get('view/{id}', 'PackageController@view')->name('package.view');
                Route::get('create', 'PackageController@create')->name('package.create');
                Route::post('create', 'PackageController@store');
                Route::get('update/{id}', 'PackageController@edit')->name('package.edit');
                Route::patch('update/{id}', 'PackageController@update');
                Route::post('destroy/{id}', 'PackageController@destroy')->name('package.destroy');
                Route::get('destination', 'PackageController@getPackages')->name('package.destination');
            });

            //Enquiry
            Route::resource('enquiry', 'EnquiryController');
            Route::group(['prefix' => 'blog'], function () {
                Route::get('/', 'BlogController@list')->name('blog.list');
                Route::post('/delete/{id}', 'BlogController@delete')->name('blog.destroy');
            });

            //Bookings
            Route::group(['prefix' => 'booking-list'], function () {
                Route::get('/package', 'BookingController@package')->name('booking.package.list');
                Route::get('/adventure', 'BookingController@adventure')->name('booking.adventure.list');
                Route::get('/booking_detail/{id}', 'BookingController@bookingDetail')->name('booking.detail');
                Route::get('/booking_status/{id}', 'BookingController@status')->name('booking.status');
                Route::post('destroy/{id}', 'BookingController@destroy')->name('booking.destroy');
            });

            //Landing Slider
            Route::resource('slider', 'ImageSliderController');
        });
    });
});

app/Http/Controllers/backend/ActivitiesController.php
<?php

namespace App\Http\Controllers\backend;

use App\Activities;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Intervention\Image\Facades\Image;


class ActivitiesController extends Controller
{
    public function index()
    {
        $activities = Activities::get();
        return view('backend.activity.show', compact('activities'));
    }

    public function create(){

        $activity = null;
        return view('backend.activity.create', compact('activity'));
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|min:3|max:50',
            'description' => 'required|min:3',
            'cost' => 'numeric',
            'image' => 'image|max:1999',
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator);
        }

        $images = $request->file('image');
        $extension = $images->getClientOriginalExtension();
        $imageName = str_random() . "." . $extension;
        Image::make($images)
            ->resize(400, 265)
            ->save(public_path('/img/thumbnail/adventure/') . $imageName);
        Image::make($images)
            ->save(public_path('/img/adventure/') . $imageName);


        $activity = new Activities();
        $activity->name = $request->name;
        $activity->description = $request->description;
        $activity->location = $request->location;
        $activity->cost = $request->cost;
        $activity->videos = $request->videos;
        $activity->season = $request->season;
        $activity->transportation = $request->transportation;
        $activity->start_end = $request->start_end;
        $activity->filename = $imageName;
        $activity->meta_title = $request->meta_title;
        $activity->meta_description = $request->meta_description;
        $activity->keyword = $request->keyword;
        $activity->slug = str_slug($request->meta_title);

        $activity->save();

        return redirect()->route('activity.list')->with('success', 'Destinations created successfully');
    }

    public function edit($id){
        $activity = Activities::where('id', $id)->first();
        return view('backend.activity.create', compact('activity'));
    }

    public function update(Request $request, $id)
    {

        $activity = Activities::find($id);
        if (!$activity) {
            return redirect()->route('activity.create')->with("error", 'no activity');
        }

        $validator = Validator::make($request->all(), [
            'name' => 'required|min:3|max:50',
            'description' => 'required|min:3',
            'cost' => 'numeric',
            'image' => 'image|max:1999',
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator);
        }

        if ($request->file('image')) {
            $images = $request->file('image');

            $extension = $images->getClientOriginalExtension();
            $imageName = str_random() . "." . $extension;
            Image::make($images)
                ->resize(400, 265)
                ->save(public_path('/img/thumbnail/adventure/') . $imageName);
            Image::make($images)
                ->save(public_path('/img/adventure/') . $imageName);


            $adventureImg = public_path("/img/adventure/" . $activity->filename);
            if (file_exists($adventureImg)) {
                @unlink($adventureImg);

            }
            $adventureImg = public_path("/img/thumbnail/adventure/" . $activity->filename);
            if (file_exists($adventureImg)) {
                @unlink($adventureImg);
            }
            $activity->filename = $imageName;
        }

        $activity->name = $request->name;
        $activity->description = $request->description;
        $activity->location = $request->location;
        $activity->cost = $request->cost;
        $activity->videos = $request->videos;
        $activity->season = $request->season;
        $activity->transportation = $request->transportation;
        $activity->start_end = $request->start_end;
        $activity->meta_title = $request->meta_title;
        $activity->meta_description = $request->meta_description;
        $activity->keyword = $request->keyword;
        $activity->slug = str_slug($request->meta_title);

        $activity->save();

        return redirect()->route('activity.list')->with('success', 'Activity updated successfully');
    }

    public function destroy($id){

        $activity =  Activities::findOrFail($id);
        $adventureImg = public_path("/img/adventure/" . $activity->filename);
        if (file_exists($adventureImg)) {
            @unlink($adventureImg);

        }
        $adventureImg = public_path("/img/thumbnail/adventure/" . $activity->filename);
        if (file_exists($adventureImg)) {
            @unlink($adventureImg);
        }
        $activity->delete();
        return redirect()->route('activity.list')->with('success', ' Activity deleted.');
    }
}

app/Http/Controllers/backend/BlogController.php
<?php

namespace App\Http\Controllers\backend;

use App\Blog;
use App\WebsiteUser;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class BlogController extends Controller
{
    public function list(){
        $blogs = DB::table('users')
            ->join('blogs', 'users.id', '=', 'blogs.users_id')
            ->select('users.name as writer', 'blogs.*')
            ->get();
        return view('backend.blog.blog')->with('blogs', $blogs);
    }

    public function delete($id){

        $blog = Blog::find($id);
        $blogImg = public_path("/img/blog/" . $blog->image);
        if (file_exists($blogImg)) {
            @unlink($blogImg);
        }
        $blogImg = public_path("/img/thumbnail/blog/" . $blog->image);
        if (file_exists($blogImg)) {
            @unlink($blogImg);
        }
        $blog->delete();

        return redirect()->route('blog.list');
    }
}

app/Http/Controllers/backend/BookingController.php
<?php

namespace App\Http\Controllers\backend;

use App\AdventureBooking;
use App\Booking;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BookingController extends Controller
{
    public function package()
    {
        $bookings=Booking::whereNotNull('package_id')->get();
        return view('backend.booking.package',compact('bookings'));
    }

    public function adventure()
    {
        $bookings=Booking::whereNotNull('adventure_id')->get();
        return view('backend.booking.adventure',compact('bookings'));
    }

    public function bookingDetail($id){
        $booking=Booking::where('id',$id)->first();
        return view('backend.booking.bookingDetail',compact('booking'));
    }

    public function status($id){
        $booking =  Booking::findOrFail($id);
        $booking->status = true;
        $booking->save();
        return redirect()->route('booking.detail', $booking->id);
    }

    public function destroy($id){
        $booking =  Booking::findOrFail($id);
        $booking->delete();
        return redirect()->route('booking.list')->with('success', 'Deleted Successfully');
    }

}

resources/views/backend/slider/create.blade.php
@extends('backend.layout.master')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Slider's Image Create</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ Route('dashboard') }}">Image Slider</a></li>
                        <li class="breadcrumb-item active">Create</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content" style="margin-left: 5vh;">
        <div class="row">
            <div class="col-md-6">

                @if ($errors->any())
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif

                <form method="POST" action="{{ route('slider.store') }}" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8">

                                <div class="form-group-lg">
                                    <label for="image">Select images for slider</label>
                                    <input type="file" class="form-control-file" id="image" name="image" multiple required>
                                </div>
                                <div class="form-group-lg">
                                    <label></label>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary btn-sm">Upload</button>
                                    <button type="reset" class="btn btn-dark btn-sm">Reset</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </section>
    <!-- /.content -->
@endsection

resources/views/backend/slider/slider.blade.php
@extends('backend.layout.master')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Slider's Image List</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ Route('dashboard') }}">Image Slider</a></li>
                        <li class="breadcrumb-item active">List</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-info">
                    <div class="box-header">
                        <div class="box-tools float-lg-left">
                            @if(Session::has('message'))
                                {{ Session::get('message') }}
                            @endif
                        </div>
                        <div class="box-tools float-lg-right">
                            <a class="btn btn-info btn-sm" href="{{ Route('slider.create') }}"><i
                                        class="fa fa-plus-circle"></i> Add New Image</a>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body margin-top-20">
                        <div class="table-responsive">
                            <table id="listDataTable"
                                   class="table table-bordered table-striped list_view_table display responsive no-wrap"
                                   width="100%">
                                <thead>
                                <tr>
                                    <th width="10%">#</th>
                                    <th width="50%">Image</th>
                                    <th class="notexport" width="20%">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($sliders as $slider)
                                    <tr>
                                        <td>{{$loop->iteration}}</td>
                                        <td>
                                            <img class="img-responsive center" style="height: 35px; width: 35px;" src="{{ asset('/img/slider/'. $slider->filename) }}" alt="slider image">
                                        </td>

                                        <td>
                                            <div class="btn-group">
                                                <form method="POST" action="{{route('slider.destroy', $slider->id)}}">
                                                    {{ csrf_field() }}
                                                    {{ method_field('DELETE') }}
                                                    <input name="_method" type="hidden" value="DELETE">
                                                    <button type="submit" class="btn btn-danger btn-sm" title="Delete">
                                                        <i class="fa fa-fw fa-trash"></i>
                                                    </button>
                                                </form>
                                            </div>

                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>

    </section>
    <!-- /.content -->
@endsection